### PR TITLE
original commit of week2 problem set

### PR DESCRIPTION
**Pull request by vaga3461**
This is my week 2 problem set, in need of peer review

### CODE REVIEW

**Comment by vaga3461** [comment]
Here's a binder link for reviewers: <a href='https://mybinder.org/v2/gh/CUB-Computational-Tools/2020-ps-vaga3461/binder-python?urlpath=git-pull?repo=https%3A%2F%2Fgithub.com%2FCUB-Computational-Tools%2F2020-ps-vaga3461%26branch%3Dweek2%26urlpath%3Dlab'></a>

**Review by jolsenvaldez — CHANGES_REQUESTED** [review]
Is this the most up-to-date file for review? I'm not seeing the images properly and some of the text has symbols embedded? It might also be me because I've been having trouble looking in the right spots for these files once they're remote.

**Comment by vaga3461** [comment]
I think it is in terms of content, but the image problem is because I'm having trouble adding the "images" folder that I made on my local branch to the git repo, so when I push my changes from local to remote the images aren't being included. I'm trying a workaround now, which will be to just add my images to the preexisting "data" folder.

**Comment by vaga3461** [comment]
update: the images should appear now!

**Review by jolsenvaldez — APPROVED** [review]
This looks great to me! Images showed up, code runs through, explanations are solid (though I think stress and strain are always hard terms to explain and complete labs on, so I'm sure you'll be prepared to get a lot of questions on this lab). Good luck with it tomorrow!

**Pull request merged**
